<a href="https://colab.research.google.com/github/rifaa14/bigdata/blob/main/Tugas2_BigData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import numpy
import numpy
#cek versi
numpy.__version__

'1.19.5'

In [2]:
import numpy as np

In [3]:
#menampilkan semua konten namespace numpy
#np.<TAB>

In [4]:
#menampilkan dokumentasi bawaan numpy
np?

### A Python List Is More Than Just A List

In [5]:
#python list
#membuat list integer
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
type(L[0])

int

In [7]:
#list string
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [8]:
type(L2[0])

str

In [9]:
#list heterogen
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

### Fixed-Type Arrays in Python

In [10]:
#membuat array
import array
L = list(range(10))
A = array.array('l',L)
A

array('l', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating Arrays from Python Lists

In [11]:
#membuat array dari python list
#integer array
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [12]:
#numpy hanya bisa membuat array dengan tipe yang sama, jika tidak sama maka numpy akan upcast.
#misalnya disini integer upcast ke float
np.array([3.14, 4, 2, 3])


array([3.14, 4.  , 2.  , 3.  ])

In [13]:
#jika kita ingin menentukan tipe datanya secara langsung, kita dapat menggunakan dtype
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [14]:
#numpy dapat menginisialisasi array multidimensi menggunakan list of list
np.array([range(l,l+3) for l in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [15]:
#membuat 10 array integer dengan 0
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
#membuat array 3x5 float dengan 1
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#membuat array 3x5 float dengan 1
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [18]:
# Membuat array yang diisi dengan urutan linier
# Mulai dari 0 sampai 20 dengan jarak 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
#memuat array dari lima nilai dengan jarak yang sama antara 0 dan 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
#membuat array 3x3 dengan nilai acak antara 0 dan 1
np.random.random((3,3))

array([[0.25072976, 0.4654427 , 0.98903189],
       [0.15445696, 0.27921617, 0.93919571],
       [0.04068667, 0.88255438, 0.12873268]])

In [21]:
#membuat array 3x3 dengan nilai acak terdistribusi normal
#dengan mean 0 dan deviasi standar 1
np.random.normal(0,1,(3,3))

array([[ 0.70605699, -0.45137418, -0.03461773],
       [ 1.19518368, -0.72683716,  1.68377529],
       [ 0.61691071, -2.79726816,  1.22722394]])

In [22]:
#membuat array 3x3 dengan random integer pada interval[0,10]
np.random.randint(0,10,(3,3))

array([[2, 9, 6],
       [5, 0, 2],
       [5, 2, 4]])

In [23]:
#membuat matrix identitas 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#membuat 3 integer array yang tidak diinisialisasi
#dengan values yang akan menjadi apapun yang sudah ada di lokasi memori
np.empty(3)

array([1., 1., 1.])

### NumPy Array Attributes

In [25]:
import numpy as np
np.random.seed(0) #seed untuk reproduktifitas

x1 = np.random.randint(10, size=6) #array satu dimensi
x2 = np.random.randint(10, size=(3,4)) #array dua dimensi
x3 = np.random.randint(10, size=(3,4,5)) #array tiga dimensi

In [26]:
#setiap array memiliki atribut ndim (jumlah dimensi), shape(ukuran masing-masing
#dimensi), dan size (ukuran total array)
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [27]:
print("dtype: ",x3.dtype)

dtype:  int64


In [28]:
#atribut lain termasuk ukuran item, yang mencantumkan ukuran (dalam byte) dari setiap elemen array,
#dan nbytes, yang mencantumkan ukuran total (dalam byte) dari array
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

itemsize:  8 bytes
nbytes:  480 bytes


### Array Indexing:Accessing Single Elements

In [29]:
x1

array([5, 0, 3, 3, 7, 9])

In [30]:
#akses satu element
x1[0]

5

In [31]:
x1[4]

7

In [32]:
#untuk akses index dari akhir array, menggunakan tanda negatif
x1[-1]

9

In [33]:
x1[-2]

7

In [34]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [35]:
#pada array multidimensional, akses item menggunakan koma
x2[0,0]

3

In [36]:
x2[2,0]

1

In [37]:
x2[2,-1]

7

In [38]:
#mengubah value menggunakan notasi index
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [39]:
#tidak sama dengan python lists, numpy array memiliki tipe tetap. 
#artinya, jika kita memasukkan nilai float ke dalam array integer
#maka nilai akan terpotong
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

### Array Slicing : Accessing Subarrays

In [40]:
#subarrays satu dimensi
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
x[:5] #elemen pertama sampai 5

array([0, 1, 2, 3, 4])

In [42]:
x[5:] #elemen sesudah index ke5

array([5, 6, 7, 8, 9])

In [43]:
x[4:7] #subarray tengah

array([4, 5, 6])

In [44]:
x[::2] #setiap elemen lainnya

array([0, 2, 4, 6, 8])

In [45]:
x[1::2] #setiap elemen lain, dimulai dari index 1

array([1, 3, 5, 7, 9])

In [46]:
x[::-1] #membalik urutan semua elemen

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [47]:
x[5::-2] #membalik dari index 5

array([5, 3, 1])

In [48]:
#subarrays multidimensi
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [49]:
x2[:2,:3] #dua baris, tiga kolom)

array([[12,  5,  2],
       [ 7,  6,  8]])

In [50]:
x2[:3,::2] #semua baris, setiap kolom lain

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [51]:
#subarray dapat dibalikkan bersama
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [52]:
#Mengakses baris dan kolom array.
#mengakses single baris atau kolom dari sebuah larik.
#dapat dilakukan dengan menggabungkan indeks dan slicing,
#menggunakan irisan kosong yang ditandai dengan satu titik dua (:):
print(x2[:,0]) #kolom pertama x2

[12  7  1]


In [53]:
print(x2[0,:]) #baris pertama x2

[12  5  2  4]


In [54]:
print(x2[0]) #sama dengan x2[0,:]

[12  5  2  4]


In [55]:
#subarrays no-copy views
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [56]:
#extract subarray 2x2
x2_sub = x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [57]:
#jika kita memodifikasi subarray, maka array original akan berubah juga
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [58]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [59]:
#membuat salinan array
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [60]:
#jika kita memodifikasi salinan array ini, maka array original tidak tersentuh
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [61]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping of Arrays

In [62]:
#jika kita ingin membentuk array 3x3 kita dapat menggunakan reshape()
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
#pola reshape umum lainnya adalah konversi larik satu dimensi menjadi matriks baris atau kolom dua dimensi
x = np.array([1,2,3])

#baris vektor melalui reshape
x.reshape((1,3))

array([[1, 2, 3]])

In [64]:
#baris baru melalui newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [65]:
#kolom vektor melalui reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [66]:
#kolom vektor melalui newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting

In [67]:
#concatenation of arrays
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [68]:
#kita juga dapat menggabungkan array lebih dari dua dalam satu waktu
z = [99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [69]:
#np.concatenate juga dapat digunakan untuk array dua dimensi
grid = np.array([[1,2,3],
                 [4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [70]:
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [71]:
#Untuk array dengan dimensi campuran, akan lebih jelas menggunakan np.vstack
#fungsi (tumpukan vertikal) dan np.hstack (tumpukan horizontal)
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])
#vertikal stack array
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [72]:
#horizontal stack arrays
y = np.array([[99],
              [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [73]:
#splitting of arrays
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [74]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
#split vertikal
upper, lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [76]:
#split horizontal
left,right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
